#!/usr/bin/env python
import gevent.monkey
gevent.monkey.patch_all()

import os
import io
import curses
import optparse
import re
import time
import socket
import curses
import StringIO

class GearmanClusterStatus(object):
    """collection of GearmanServerStatus"""
    def __init__(self, servers, workers=None, options=None):
        self.servers = servers
        self.workers = workers # workers to watch
        self.cluster_workers = {}
        self.options = options
        self.server_status = {}
        for server in self.servers:
            host, port = (server.split(':') + [4730])[:2]
            self.server_status[server] = GearmanServerStatus(host, int(port), options)

    def update(self):
        """Refresh the collection of GearmanServerStatus"""
        self.cluster_workers.clear()
        threads = []
        for server, status in self.server_status.iteritems():
            threads.append(gevent.spawn(status.update))
        gevent.joinall(threads)

        for server,status in self.server_status.iteritems():
            for worker in status.workers:
                if worker.name not in self.cluster_workers:
                    self.cluster_workers[worker.name] = GearmanClusterWorkerStatus(worker.name)

                # summ up the workers
                self.cluster_workers[worker.name].jobs_queued += worker.jobs_queued
                self.cluster_workers[worker.name].jobs_running += worker.jobs_running
                self.cluster_workers[worker.name].workers_running += worker.workers_running
                self.cluster_workers[worker.name].server_count += 1;

    def __repr__(self):
        result = ''
        self.update()
        for worker in self.cluster_workers:
            result += '%s\n' % self.cluster_workers[worker]

        if options.detailed:
            result += '-' * 72
            result += "\n";
            for server in self.servers:
                result += 'host: %s\tw: %s\n' % (server, len(self.server_status[server].workers))
                result += str(self.server_status[server])

        return result
        
class GearmanServerStatus(object):
    """collection of GearmanWorkerStatus objects"""
    def __init__(self, host, port=4730, options=None):
        self.host = host
        self.port = port
        self.workers = list()
        self.errors = list()
       
    def update(self):
        """connects to and issues a stats command to gearmand"""
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        fs = None
        try:
            s.connect((self.host, self.port))
            fs = s.makefile('wb+')
        except:
            self.errors.append('failed to connect')
            return

        # remove any previous run data
        del(self.workers[:])

        while True:
            fs.write('status\n');
            fs.flush()

            line = fs.readline()
            if line == '.\n':
                break

            status = GearmanWorkerStatus(line, options)

            # if not options.workers or status.name in options.workers:  
            if not options.workers:
                self.workers.append(status)
            else:
                for pattern in options.workers:
                    result  = re.match(pattern, status.name)
                    if result is not None and result.group:
                        self.workers.append(status)
                        # only match the first regex
                        break

        fs.close()
        s.close()

    def __repr__(self):
        result = ''
        for worker in self.workers:
           result += '%s\n' % worker
        if len(self.errors):
            result += '%s\n' % str(self.errors)
        return result

class GearmanWorkerStatus(object):
    """A single worker status returned by gearmand"""

    def __init__(self, status_line, options=None):
        self.name = ''
        self.workers_running = 0
        self.jobs_queued = 0
        self.jobs_running = 0
        self.process_status_line(status_line)

    def process_status_line(self, status_line):
        """parse gearman status line"""

        result = re.match('^([a-z0-9A-Z_]+)\s+(\d+)\s+(\d+)\s+(\d+)', 
            status_line
        )
        if result.group:
            self.name = result.group(1)
            self.jobs_queued = int(result.group(2))
            self.jobs_running = int(result.group(3))
            self.workers_running = int(result.group(4))
        else:
            raise GearmanWorkerStatusLineError(
                "bad status - '%s'" % status_line)

    def __repr__(self):
        return "\tq: %d\tr: %d\tw: %d\tworker: %s" % (
            self.jobs_queued, 
            self.jobs_running, 
            self.workers_running,
            self.name 
        )

class GearmanWorkerStatusLineError(Exception):
    pass

class GearmanClusterWorkerStatus(GearmanWorkerStatus):
    """workers running in the cluster"""
    def __init__(self, worker):
        self.name = worker
        self.jobs_queued = 0
        self.jobs_running = 0
        self.workers_running = 0
        self.server_count = 0 # number of servers job is running on

    def update(self, jobs_queued, jobs_running, workers_running):
        """upate the counts for the worker"""
        self.jobs_queued += jobs_queued
        self.jobs_running += jobs_running
        self.workers_running += workers_running
        self.server_count += 1

    def __repr__(self):
        return "s: %d\tq: %d\tr: %d\tw: %d\tworker: %s" % (
            self.server_count, 
            self.jobs_queued, 
            self.jobs_running, 
            self.workers_running,
            self.name)

#    home_dir = os.getenv('USERPROFILE') or os.getenv('HOME')
#    if path.exists('/etc/gmstatus') and 

def read_config(config_file):
    """read a gmstatus config file and parse it"""
    config = {}
    try:
        FH = open(config_file)
        for line in FH.readlines():
            if '=' not in line:
                continue
            (key, value) = line.strip().split('=');
            if key not in config:
                config[key] = list()
            config[key].append(value)
        FH.close()
    except IOError:
        pass
    return config;

def get_config(config_files):
    """read config files until we find one"""
    for file in config_files:
        if os.path.exists(file):
            return read_config(file)

if __name__ == '__main__':
    parser = optparse.OptionParser()

    parser.add_option("-i", "--interval", metavar="NUMBER", type="float", 
        help="workers to display, can give multiple options")

    parser.add_option("-c", "--config", metavar="STRING", type="string", 
        help="specify config file to use")

    parser.add_option("-w", "--workers", action='append', default=[],
        help="workers to display, can give multiple options")

    parser.add_option("-d", "--detailed", action="store_true", default=False,
        help="display detailed results for each server")

    (options, args) = parser.parse_args()

    # default config file locations
    config_files = ['.gmstatus', os.getenv('HOME') + '/.gmstatus', '/etc/gmstatus']
    
    if options.config:
        config_files = [options.config]

    config = get_config(config_files)

    servers = args
    
    if not servers and config:
        servers = config['server']

    if not servers:
        # no config found default to localhost:4730
        servers = ['localhost:4730']

    if len(options.workers) == 0:
        if 'worker' in config:
            options.workers = config['worker']
        else:
            options.workers = None

    cluster = GearmanClusterStatus(servers, options.workers, options)
    key = -1;
    if not options.interval:
        print cluster
    else:
        screen = curses.initscr()
        screen.nodelay(1)
        try:
            while True:
                output = str(cluster)
                screen.erase()
                (height, width) = screen.getmaxyx()
                size = (height*width)
                cnt=0
                for line in output.split('\n'):
                   cnt += 1
                   if cnt >= height:
                       break
                   screen.addstr(cnt, 0, line)

                screen.refresh()
                key = screen.getch()
                if key == -1:
                    screen.timeout(int(options.interval*1000))
                elif key == ord(' '):
                    continue
                elif key == ord('d'):
                    if options.detailed == True:
                        options.detailed = False;
                    else:
                        options.detailed = True;
                    continue
                elif key == ord('q'):
                    break
                elif key == ord('?') or key == ord('h'):
                    screen.addstr(0, 0, "(d)etails (q)uit (h)elp (' ')refresh")
                    screen.refresh()
                else:
                    print "KEY %s" % (key)

        finally:
            curses.endwin();
